# LENDING CLUB

# PRÉ-PROCESSAMENTO DOS DADOS

# 1. IMPORTANDO BIBLIOTECAS

In [2]:
import numpy as np
import pandas as pd

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns

# Modelagem
import statsmodels.api as sm                       # regressão logística com p-valores
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, roc_curve

# Configurações de exibição
pd.set_option('display.max_columns', None)         # mostra todas as colunas
pd.set_option('display.max_rows', 100)
pd.set_option('display.float_format', lambda x: f'{x:.4f}')

# Estilo dos gráficos
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 5)

# Silenciar avisos não críticos
import warnings
warnings.filterwarnings('ignore')

# 2. CONJUNTO DE DADOS

In [3]:
df = pd.read_csv('dados/lending_club_2007_2014.csv', index_col=0)

print(f'Linhas: {df.shape[0]:,}')
print(f'Colunas: {df.shape[1]}')
df.head()

Linhas: 466,285
Colunas: 74

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,1077501,1296599,5000,5000,4975.0000,36 months,10.6500,162.8700,B,B2,NaN,10+ years,RENT,24000.0000,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.6500,0.0000,Jan-85,1.0000,NaN,NaN,3.0000,0.0000,13648,83.7000,9.0000,f,0.0000,0.0000,5861.0714,5831.7800,5000.0000,861.0700,0.0000,0.0000,0.0000,Jan-15,171.6200,NaN,Jan-16,0.0000,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1077430,1314167,2500,2500,2500.0000,60 months,15.2700,59.8300,C,C4,Ryder,< 1 year,RENT,30000.0000,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.0000,0.0000,Apr-99,5.0000,NaN,NaN,3.0000,0.0000,1687,9.4000,4.0000,f,0.0000,0.0000,1008.7100,1008.7100,456.4600,435.1700,0.0000,117.0800,1.1100,Apr-13,119.6600,NaN,Sep-13,0.0000,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1077175,1313524,2400,2400,2400.0000,36 months,15.9600,84.3300,C,C5,NaN,10+ years,RENT,12252.0000,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.7200,0.0000,Nov-01,2.0000,NaN,NaN,2.0000,0.0000,2956,98.5000,10.0000,f,0.0000,0.0000,3003.6536,3003.6500,2400.0000,603.6500,0.0000,0.0000,0.0000,Jun-14,649.9100,NaN,Jan-16,0.0000,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1076863,1277178,10000,10000,10000.0000,36 months,13.4900,339.3100,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0000,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.0000,0.0000,Feb-96,1.0000,35.0000,NaN,10.0000,0.0000,5598,21.0000,37.0000,f,0.0000,0.0000,12226.3022,12226.3000,10000.0000,2209.3300,16.9700,0.0000,0.0000,Jan-15,357.4800,NaN,Jan-15,0.0000,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1075358,1311748,3000,3000,3000.0000,60 months,12.6900,67.7900,B,B5,University Medical Group,1 year,RENT,80000.0000,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.9400,0.0000,Jan-96,0.0000,38.0000,NaN,15.0000,0.0000,27783,53.9000,38.0000,f,766.9000,766.9000,3242.1700,3242.1700,2233.1000,1009.0700,0.0000,0.0000,0.0000,Jan-16,67.7900,Feb-16,Jan-16,0.0000,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 3. ORDENAÇÃO POR ORDEM CRONOLÓGICA

In [6]:
# issue_d vem como "Dec-11" (ano com 2 dígitos), então usamos %b-%y.
df['issue_d'] = pd.to_datetime(df['issue_d'], format='%b-%y')

# Ordena cronologicamente pela data de emissão
df = df.sort_values(by='issue_d', ascending=True).reset_index(drop=True)

# Confere o intervalo de datas
print(f"Data mais antiga: {df['issue_d'].min()}")
print(f"Data mais recente: {df['issue_d'].max()}")
df[['issue_d', 'id']].head()

Data mais antiga: 2007-06-01 00:00:00
Data mais recente: 2014-12-01 00:00:00

     issue_d     id
0 2007-06-01  85781
1 2007-06-01  87023
2 2007-06-01  88637
3 2007-06-01  88046
4 2007-06-01  85961

# 4. VALORES FALTANTES

In [7]:
missing_df = (
    df.isna().sum()
    .to_frame()
    .rename(columns={0: 'count'})
    .sort_values(by='count', ascending=False)
)
missing_df['pct'] = round(missing_df['count'] / df.shape[0] * 100, 3)
missing_df

                              count      pct
inq_last_12m                 466285 100.0000
verification_status_joint    466285 100.0000
open_acc_6m                  466285 100.0000
open_il_6m                   466285 100.0000
open_il_12m                  466285 100.0000
open_il_24m                  466285 100.0000
mths_since_rcnt_il           466285 100.0000
dti_joint                    466285 100.0000
total_bal_il                 466285 100.0000
annual_inc_joint             466285 100.0000
il_util                      466285 100.0000
open_rv_12m                  466285 100.0000
open_rv_24m                  466285 100.0000
max_bal_bc                   466285 100.0000
all_util                     466285 100.0000
inq_fi                       466285 100.0000
total_cu_tl                  466285 100.0000
mths_since_last_record       403647  86.5670
mths_since_last_major_derog  367311  78.7740
desc                         340304  72.9820
mths_since_last_delinq       250351  53.6910
next_pymnt_d                 227214  48.7290
tot_coll_amt                  70276  15.0710
tot_cur_bal                   70276  15.0710
total_rev_hi_lim              70276  15.0710
emp_title                     27588   5.9170
emp_length                    21008   4.5050
last_pymnt_d                    376   0.0810
revol_util                      340   0.0730
collections_12_mths_ex_med      145   0.0310
last_credit_pull_d               42   0.0090
open_acc                         29   0.0060
pub_rec                          29   0.0060
total_acc                        29   0.0060
inq_last_6mths                   29   0.0060
earliest_cr_line                 29   0.0060
delinq_2yrs                      29   0.0060
acc_now_delinq                   29   0.0060
title                            21   0.0050
annual_inc                        4   0.0010
collection_recovery_fee           0   0.0000
application_type                  0   0.0000
policy_code                       0   0.0000
last_pymnt_amnt                   0   0.0000
id                                0   0.0000
recoveries                        0   0.0000
pymnt_plan                        0   0.0000
loan_amnt                         0   0.0000
funded_amnt                       0   0.0000
funded_amnt_inv                   0   0.0000
term                              0   0.0000
int_rate                          0   0.0000
installment                       0   0.0000
grade                             0   0.0000
sub_grade                         0   0.0000
home_ownership                    0   0.0000
verification_status               0   0.0000
issue_d                           0   0.0000
loan_status                       0   0.0000
url                               0   0.0000
total_rec_late_fee                0   0.0000
purpose                           0   0.0000
zip_code                          0   0.0000
addr_state                        0   0.0000
dti                               0   0.0000
revol_bal                         0   0.0000
initial_list_status               0   0.0000
out_prncp                         0   0.0000
member_id                         0   0.0000
total_pymnt                       0   0.0000
total_pymnt_inv                   0   0.0000
total_rec_prncp                   0   0.0000
total_rec_int                     0   0.0000
out_prncp_inv                     0   0.0000

In [8]:
# Verificação de duplicados
print(f'Linhas totalmente duplicadas: {df.duplicated().sum()}')
print(f'IDs duplicados: {df["id"].duplicated().sum()}')

Linhas totalmente duplicadas: 0
IDs duplicados: 0

In [9]:
# Colunas com 70% ou mais de valores ausentes (candidatas a remoção)
limite_ausencia = 70
cols_alta_ausencia = missing_df[missing_df['pct'] >= limite_ausencia].index.tolist()

print(f'Colunas com >= {limite_ausencia}% de ausência: {len(cols_alta_ausencia)}')
cols_alta_ausencia

Colunas com >= 70% de ausência: 20

['inq_last_12m',
 'verification_status_joint',
 'open_acc_6m',
 'open_il_6m',
 'open_il_12m',
 'open_il_24m',
 'mths_since_rcnt_il',
 'dti_joint',
 'total_bal_il',
 'annual_inc_joint',
 'il_util',
 'open_rv_12m',
 'open_rv_24m',
 'max_bal_bc',
 'all_util',
 'inq_fi',
 'total_cu_tl',
 'mths_since_last_record',
 'mths_since_last_major_derog',
 'desc']

### Remoção de variáveis com alta ausência

Estabelecemos um corte de 70%: variáveis com 70% ou mais de valores ausentes são removidas, pois a imputação em volume tão alto introduziria viés. As 20 colunas identificadas se enquadram em quatro motivos:

- **Variáveis de co-tomador** (`annual_inc_joint`, `dti_joint`, `verification_status_joint`): preenchidas apenas em aplicações conjuntas, que são minoria. Ausência estrutural.
- **Variáveis de linhas de crédito parceladas e rotativas** (`open_acc_6m`, `open_il_6m`, `open_il_12m`, `open_il_24m`, `mths_since_rcnt_il`, `total_bal_il`, `il_util`, `open_rv_12m`, `open_rv_24m`, `max_bal_bc`, `all_util`, `inq_fi`, `total_cu_tl`, `inq_last_12m`): passaram a ser coletadas apenas em parte do período, ficando vazias nos empréstimos anteriores. Ausência por disponibilidade temporal.
- **Variáveis de tempo desde o último evento** (`mths_since_last_record`, `mths_since_last_major_derog`): vazias quando o evento nunca ocorreu. Embora o vazio tenha significado, a proporção de ausência é alta demais para tratá-las como categoria.
- **Texto livre** (`desc`): descrição não estruturada preenchida pelo tomador, sem utilidade para o modelo.

In [10]:
# Remoção das colunas com ausência >= 70%
df = df.drop(columns=cols_alta_ausencia)

print(f'Colunas removidas: {len(cols_alta_ausencia)}')
print(f'Shape atual: {df.shape}')

Colunas removidas: 20
Shape atual: (466285, 54)

### Investigação dos valores ausentes remanescentes

Removidas as variáveis com alta ausência, investigamos as que restaram para decidir o tratamento. A ausência não é tratada de forma única: seu significado depende da causa. Analisamos a distribuição de `loan_status` nas linhas com ausência (para verificar se o vazio está associado a mais risco) e a natureza de cada variável, classificando cada caso em remover a observação, imputar um valor com significado ou tratar o vazio como categoria própria.

In [11]:
# Ausentes remanescentes (colunas que ainda têm algum vazio)
missing_restante = (
    df.isna().sum()
    .to_frame(name='count')
    .query('count > 0')
    .sort_values('count', ascending=False)
)
missing_restante['pct'] = round(missing_restante['count'] / df.shape[0] * 100, 3)
missing_restante

                             count     pct
mths_since_last_delinq      250351 53.6910
next_pymnt_d                227214 48.7290
total_rev_hi_lim             70276 15.0710
tot_cur_bal                  70276 15.0710
tot_coll_amt                 70276 15.0710
emp_title                    27588  5.9170
emp_length                   21008  4.5050
last_pymnt_d                   376  0.0810
revol_util                     340  0.0730
collections_12_mths_ex_med     145  0.0310
last_credit_pull_d              42  0.0090
inq_last_6mths                  29  0.0060
earliest_cr_line                29  0.0060
open_acc                        29  0.0060
pub_rec                         29  0.0060
total_acc                       29  0.0060
delinq_2yrs                     29  0.0060
acc_now_delinq                  29  0.0060
title                           21  0.0050
annual_inc                       4  0.0010

In [12]:
# emp_length: a ausência está associada a mais risco?
print('--- loan_status onde emp_length é ausente ---')
print(df.loc[df['emp_length'].isna(), 'loan_status'].value_counts(normalize=True) * 100)

--- loan_status onde emp_length é ausente ---
loan_status
Current                                               55.6026
Fully Paid                                            30.2313
Charged Off                                           11.0529
Late (31-120 days)                                     1.9088
In Grace Period                                        0.4855
Late (16-30 days)                                      0.3284
Default                                                0.2285
Does not meet the credit policy. Status:Fully Paid     0.0904
Does not meet the credit policy. Status:Charged Off    0.0714
Name: proportion, dtype: float64

### Remoção de colunas irrelevantes e de vazamento

Além das variáveis com alta ausência, removemos dois grupos. O primeiro reúne identificadores e campos sem valor preditivo: `id`, `member_id`, `url`, `zip_code`, `title`, `emp_title`, `application_type`, `pymnt_plan` e `policy_code`. O segundo reúne variáveis que só passam a existir após a concessão do empréstimo e que, portanto, constituiriam vazamento de informação: `next_pymnt_d`, `last_pymnt_d`, `last_credit_pull_d`, `funded_amnt_inv`, `total_pymnt_inv` e `out_prncp_inv`.

In [13]:
# Colunas irrelevantes (identificadores, texto livre, baixa variância)
cols_irrelevantes = [
    'id', 'member_id', 'url', 'zip_code', 'title', 'emp_title',
    'application_type', 'pymnt_plan', 'policy_code'
]

# Colunas de vazamento (só existem após a concessão do empréstimo)
cols_vazamento = [
    'next_pymnt_d', 'last_pymnt_d', 'last_credit_pull_d',
    'funded_amnt_inv', 'total_pymnt_inv', 'out_prncp_inv'
]

df = df.drop(columns=cols_irrelevantes + cols_vazamento)
print(f'Colunas removidas nesta etapa: {len(cols_irrelevantes + cols_vazamento)}')
print(f'Shape atual: {df.shape}')

Colunas removidas nesta etapa: 15
Shape atual: (466285, 39)

### Tratamento dos valores ausentes remanescentes

Aplicamos dois tratamentos distintos conforme a natureza da ausência. As variáveis com pouquíssimos ausentes (`annual_inc`, `total_acc`, `acc_now_delinq`, `pub_rec`, `open_acc`, `delinq_2yrs`, `earliest_cr_line`, `inq_last_6mths`) somam apenas 29 registros; dado o tamanho da base, removemos essas observações em vez de imputá-las, evitando introduzir viés. Para `emp_length`, cuja ausência se mostrou não associada a maior risco de default, imputamos "0 years", interpretando o vazio como ausência de experiência profissional formal.

In [15]:
# Remoção das observações com ausência ínfima (29 registros no total)
cols_dropna = ['annual_inc', 'total_acc', 'acc_now_delinq', 'pub_rec',
               'open_acc', 'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths']
df = df.dropna(subset=cols_dropna)

# Imputação de emp_length: vazio interpretado como sem experiência formal
df['emp_length'] = df['emp_length'].fillna('0 years')

print(f'Shape após tratamento de ausentes: {df.shape}')

Shape após tratamento de ausentes: (466256, 39)

In [16]:
# Inspeção dos formatos antes de converter
print('term:', df['term'].unique())
print()
print('emp_length:', df['emp_length'].unique())
print()
print('earliest_cr_line:', df['earliest_cr_line'].head(3).tolist())

term: [' 36 months' ' 60 months']

emp_length: ['< 1 year' '2 years' '1 year' '7 years' '8 years' '3 years' '4 years'
 '10+ years' '6 years' '5 years' '9 years' '0 years']

earliest_cr_line: ['Oct-03', 'Jan-96', 'Jul-04']

### Conversão de tipos

Três variáveis estão como texto e precisam ser convertidas para uso no modelo:

- **`term`**: vem como `' 36 months'` / `' 60 months'`. Extraímos o número e convertemos para inteiro.
- **`emp_length`**: vem em faixas textuais (`'< 1 year'` a `'10+ years'`). Convertemos para inteiro, tratando `'< 1 year'` como 0 e `'10+ years'` como 10, o que preserva a ordem da variável.
- **`earliest_cr_line`**: data da primeira linha de crédito, no formato `'Oct-03'`. Convertemos para data.

In [18]:
# term: extrai o número de meses e converte para inteiro
df['term'] = df['term'].str.extract(r'(\d+)').astype('int')
print('term:', df['term'].unique(), '| tipo:', df['term'].dtype)

term: [36 60] | tipo: int64

In [19]:
# emp_length: converte faixas textuais em inteiro (0 a 10)
df['emp_length'] = (
    df['emp_length']
    .str.replace('< 1 year', '0', regex=False)
    .str.replace('10+ years', '10', regex=False)
    .str.replace('+', '', regex=False)
    .str.replace(' years', '', regex=False)
    .str.replace(' year', '', regex=False)
    .astype('int')
)
print('emp_length:', sorted(df['emp_length'].unique()), '| tipo:', df['emp_length'].dtype)

emp_length: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10)] | tipo: int64

In [20]:
# earliest_cr_line: converte para data (formato "Oct-03")
df['earliest_cr_line'] = pd.to_datetime(df['earliest_cr_line'], format='%b-%y')
print(df['earliest_cr_line'].min(), '→', df['earliest_cr_line'].max())

1969-01-01 00:00:00 → 2068-12-01 00:00:00

### Criação de variável e correção de datas inconsistentes

Extraímos de `earliest_cr_line` a variável `mths_since_earliest_cr_line`, que mede há quantos meses o tomador abriu sua primeira linha de crédito, uma proxy de maturidade do histórico de crédito. Adotamos dezembro de 2017 como data de referência.

A conversão de datas com ano de dois dígitos gerou uma inconsistência: anos antigos (ex.: 1968) foram interpretados como futuros (2068), produzindo valores negativos de meses. Como esses casos correspondem a linhas de crédito muito antigas, imputamos o valor máximo observado da variável, preservando o significado de "primeira linha de crédito há muito tempo".

In [22]:
# Data de referência para o cálculo
DATA_REF = pd.to_datetime('2017-12-01')

# Meses desde a primeira linha de crédito, calculado pela diferença de calendário
# (evita a ambiguidade de "mês" como duração fixa)
df['mths_since_earliest_cr_line'] = (
    (DATA_REF.year - df['earliest_cr_line'].dt.year) * 12
    + (DATA_REF.month - df['earliest_cr_line'].dt.month)
)

# Diagnóstico: quantos valores ficaram negativos (efeito do ano de 2 dígitos)
n_neg = (df['mths_since_earliest_cr_line'] < 0).sum()
print(f'Valores negativos (datas mal interpretadas): {n_neg}')
print(df['mths_since_earliest_cr_line'].describe())

Valores negativos (datas mal interpretadas): 1169
count   466256.0000
mean       239.4824
std         93.9748
min       -612.0000
25%        183.0000
50%        225.0000
75%        285.0000
max        587.0000
Name: mths_since_earliest_cr_line, dtype: float64

### Correção dos valores negativos

Os 1.169 valores negativos resultam de datas antigas (anos 1960) interpretadas como futuras pela conversão de ano com dois dígitos. Como esses casos representam, na realidade, tomadores com histórico de crédito muito antigo, imputamos o valor máximo observado da variável, preservando o significado de "primeira linha de crédito estabelecida há muito tempo".

In [23]:
# Imputa o máximo observado nos casos negativos (crédito muito antigo)
maximo_valido = df['mths_since_earliest_cr_line'].max()
df.loc[df['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = maximo_valido

# Confirma que não há mais negativos
print(f'Valores negativos após correção: {(df["mths_since_earliest_cr_line"] < 0).sum()}')
print(df['mths_since_earliest_cr_line'].describe())

Valores negativos após correção: 0
count   466256.0000
mean       242.3854
std         86.4603
min         73.0000
25%        184.0000
50%        226.0000
75%        285.0000
max        587.0000
Name: mths_since_earliest_cr_line, dtype: float64

In [24]:
# Categorias de loan_status antes de definir o alvo
df['loan_status'].value_counts()

loan_status
Current                                                224226
Fully Paid                                             184739
Charged Off                                             42475
Late (31-120 days)                                       6900
In Grace Period                                          3146
Does not meet the credit policy. Status:Fully Paid       1962
Late (16-30 days)                                        1218
Default                                                   832
Does not meet the credit policy. Status:Charged Off       758
Name: count, dtype: int64

### Definição da variável-alvo (default)

Antes de criar o alvo, descartamos os contratos em andamento (`Current`), cujo desfecho ainda é desconhecido e que, portanto, não podem ser rotulados como bons ou maus pagadores. Em seguida, criamos a variável binária `default`, atribuindo `0` aos inadimplentes (`Charged Off`, `Late (31-120 days)`, `Default` e `Does not meet the credit policy. Status:Charged Off`) e `1` aos adimplentes. Nesta convenção, `1` representa o bom pagador, o que faz com que coeficientes positivos no modelo estejam associados a menor risco.

In [25]:
# Descarta contratos em andamento (desfecho desconhecido)
df = df[df['loan_status'] != 'Current'].copy()

# Alvo do modelo de PD: 1 = adimplente (bom pagador), 0 = inadimplente
inadimplentes = ['Charged Off', 'Late (31-120 days)',
                 'Does not meet the credit policy. Status:Charged Off', 'Default']
df['default'] = np.where(df['loan_status'].isin(inadimplentes), 0, 1)

print(f'Shape após remover Current: {df.shape}')
print()
print('Distribuição do alvo (%):')
print(df['default'].value_counts(normalize=True) * 100)

Shape após remover Current: (242030, 41)

Distribuição do alvo (%):
default
1   78.9427
0   21.0573
Name: proportion, dtype: float64